#!/bin/sh

/sbin/insmod /drivers/binfmt_script.ko
/sbin/insmod /drivers/serial_core.ko
/sbin/insmod /drivers/e1000.ko
/sbin/insmod /drivers/8250.ko
/sbin/insmod /drivers/8250_pci.ko

mount proc
mount -o remount,rw /
mount -a

clear                               
echo "My Tiny Linux Start :D ......"
echo ""
echo "Name:Wang Peiqi  ID:2014310585"

/sbin/ifconfig lo 127.0.0.1 up
/sbin/route add 127.0.0.1 lo &


ifconfig eth0 up
ip addr add 10.0.2.15/24 dev eth0
ip route add default via 10.0.2.2
